- ros_topic_name: "/wrist_camera/image_raw"
  gz_topic_name: "/wrist_camera/image_raw"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS
  frame_id: "wrist_camera_optical_frame"
  qos_profile: SENSOR_DATA

- ros_topic_name: "/wrist_camera/camera_info"
  gz_topic_name: "/wrist_camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS
  frame_id: "wrist_camera_optical_frame"
  qos_profile: SENSOR_DATA
